#spring:
#  datasource:
#  url: jdbc:h2:./devdb
#   username: sa
#  jpa:
#    hibernate:
#    ddl-auto: update



spring:
  jpa:
   properties:
    javax:
     persistence:
      validation:
        mode: none
  profiles:
     active:
       - production
        
  data:
    web:
      pageable:
       default-page-size: 10
       max-page-size: 100
       
lab-report:
    upload-path: picture-storage
---
spring:
  profiles: production
lab-report:
 upload-path: storage-production