spring:
  datasource:
    url: jdbc:h2:file:./devdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none

  profiles:
    active:
      - production

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

lab-report:
  upload-path: picture-storage
